name: Deploy
on:
  push:
    branches:
    - 'release/v[0-9]+.[0-9]+'

jobs:
  build_dot_net:
    runs-on: ubuntu-latest

    steps:
    - name: checkout your source
      uses: actions/checkout@v3
    - name: print
      run: echo Hello!

    - name: list before build
      uses: ls -l
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'

    - name: Build
      run: go build -o theapp main.go

    - name: list after build
      uses: ls -l