name: Deploy
on:
  push:
    branches:
    - 'release/v[0-9]+.[0-9]+'

jobs:
  build_golang_and_deploy:
    if: "! startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo ${{ github.event.head_commit.message }}

    - name: checkout your source
      uses: actions/checkout@v3
    - name: print
      run: echo Hello!

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'

    - name: Build
      run: go build -o theapp main.go

    - name: List files and directories
      run: ls -l

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "glorious-snails" 