name: Deploy
on:
  push:
    branches:
    - 'release/v[0-9]+.[0-9]+'

jobs:
  build_golang_and_deploy:
    if: "! startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: echo ${{ github.event.head_commit.message }}

    - name: checkout your source
      uses: actions/checkout@v3

    - name: Deploy to Railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: ${{ secrets.RAILWAY_SERVICE }}

    - name: Send data into Slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DIPSA 56 CI/CD Submission"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* ${{ secrets.FULL_NAME }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* ${{ secrets.EMAIL_ADDRESS }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* ${{ secrets.MATRICULATION_NUMBER }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* ${{ github.event.repository.html_url }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ secrets.RAILWAY_URL }}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "go to platform ",
                  "url": "${{ secrets.RAILWAY_URL }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 